### ISSUE TITLE
6-create-and-run-docker-container-for-mqtt not working for me

### ISSUE THREAD

**Issue by widiarrohman1234** [sukesh-ak/setup-mosquitto-with-docker#1]
in the 6th step, I didn't manage to run it
`sudo docker-compose -p mqtt5 up -d`

but i succeeded by running
`docker compose create`

### Note that the `docker compose create` command must be in the same directory.

![Screenshot 2023-08-28 215056](https://github.com/sukesh-ak/setup-mosquitto-with-docker/assets/58793672/e56080d5-90c8-4e04-a70a-35839ab3a478)

**Comment by sukesh-ak** [comment]
The one I used is `docker-compose` and the one you used is `docker compose`.
You can install using 
```bash
apt install docker-compose
```

Btw, you can get a MQTT  web client running with the following
```bash
docker run -d --name mqttx-web -p 80:80 emqx/mqttx-web
```

**Comment by widiarrohman1234** [comment]
thank you, this method has worked. I want to give a suggestion, is it okay if you enter the command in the documentation that you wrote. Thank You.

**Comment by sukesh-ak** [comment]
Have updated the readme. Thanks for the suggestions.
