### ISSUE TITLE
Docker  command change

### ISSUE THREAD

**Issue by kc9mne** [sukesh-ak/setup-mosquitto-with-docker#10]
Tried this on ubuntu 22.04 on AWS and "sudo docker-compose -p mqtt5 up -d" results in errors in containerconfig

After digging it looks like the format changed from issuing "docker-compose" to "docker compose" this results in it coming up with the following notes"

"mqtt/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
network mqtt5-network was found but has incorrect label com.docker.compose.network set to "mqtt5-network" (expected: "default")"

So the version format of the compose information may need to be updated as well.  It looks like the format updated too.

to resolve I removed the "Version" in the config and I made the adjustments below to the network section. it made the label "mqtt5_default" instead of the name I listed but everything appears to work with no errors.

```
networks:
  mqtt5-network:
    name: "mqtt5-network"
    driver: bridge
```

**Comment by sukesh-ak** [comment]
> Tried this on ubuntu 22.04 on AWS and "sudo docker-compose -p mqtt5 up -d" results in errors in containerconfig
> 
> After digging it looks like the format changed from issuing "docker-compose" to "docker compose" this results in it coming up with the following notes"
> 
> "mqtt/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion network mqtt5-network was found but has incorrect label com.docker.compose.network set to "mqtt5-network" (expected: "default")"
> 
> So the version format of the compose information may need to be updated as well. It looks like the format updated too.
> 
> to resolve I removed the "Version" in the config and I made the adjustments below to the network section. it made the label "mqtt5_default" instead of the name I listed but everything appears to work with no errors.
> 
> ```
> networks:
>   mqtt5-network:
>     name: "mqtt5-network"
>     driver: bridge
> ```

Please refer to Point # 6 which shows the command to install `docker-compose`
