### ISSUE TITLE
pwdfile

### ISSUE THREAD

**Issue by gabaoalb** [sukesh-ak/setup-mosquitto-with-docker#3]
Hello, first i want to say thanks for this tutorial, it helped me alot, but there was a minor misleading information, for me the right filename was **pwdfile** not **pwfile**, i dont know if it's only for me but anyway i think that is better warn you.

**Comment by sukesh-ak** [comment]
> Hello, first i want to say thanks for this tutorial, it helped me alot, but there was a minor misleading information, for me the right filename was **pwdfile** not **pwfile**, i dont know if it's only for me but anyway i think that is better warn you.

You can use any filename. Just make sure the same name is used in the config file.
