### ISSUE TITLE
add users

### ISSUE THREAD

**Issue by PrometheusWannaB3** [sukesh-ak/setup-mosquitto-with-docker#4]
nothing major but I've just followed along and had issues adding multiple users as per your step 7. Create a user/password in the pwfile

Could you refresh the wording that the -c _creates the file_ but to _add users_ you drop the -c flag? 

found that solution/answer here; https://answers.launchpad.net/mosquitto/+question/226477

**Comment by sukesh-ak** [comment]
Thank you. I will check and update it soon.

**Comment by sukesh-ak** [comment]
@PrometheusWannaB3 
Thanks for the tip. Updated now :)
